name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H 10.50.20.62 >> ~/.ssh/known_hosts

    - name: Copy files to VM
      run: |
        rsync -avz -e "ssh -i ~/.ssh/id_ed25519" ./ docker@10.50.20.62:/home/docker/app

    - name: Run Docker Compose
      run: |
        ssh -i ~/.ssh/id_ed25519 docker@10.50.20.62 'cd /home/docker/app && docker compose up -d --build'
